const dex = require('pokemagic/dex');
const fs = require('fs');

// How to:
//
// Once you have all of the images inside assets/sprites in the format of
// pokemon_name_lowercase.png, you can run this script with node and it'll
// generate the file `src/sprites.js`.

const lines = dex.getAllPokemon().map(({ form, name }) => {
  return `require('../assets/sprites/${(form || name).toLowerCase()}.png'),`;
});

const data = `// THIS FILE IS AUTOMATICALLY GENERATED. PLEASE SEE scripts/generateSprites.js
export default [
  ${lines.join('\n  ')}
]`;

fs.writeFileSync('./src/sprites.js', data, 'utf-8');
